### ISSUE TITLE
Missing mod 'vinery' in 'Create Astral Server Pack v2.0.5b'

### ISSUE THREAD

**Issue by lypoluz** [Laskyyy/Create-Astral#226]
Hi there!

The latest server files don't include the mod 'vinery'.
Here are the logs:
```

[18:23:54] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.22
[18:23:54] [ForkJoinPool-1-worker-2/WARN]: Mod letmedespawn uses the version fabric-1.0.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:23:54] [ForkJoinPool-1-worker-2/WARN]: Mod globaldataandresourcepacks uses the version 1.12.4_fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component '4_fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:23:54] [ForkJoinPool-1-worker-3/WARN]: Mod createaddition uses the version 20230211a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '20230211a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:23:54] [ForkJoinPool-1-worker-2/WARN]: Mod createsifter uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:23:54] [ForkJoinPool-1-worker-1/WARN]: Mod create uses the version 0.5.0.i-988+1.18.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'i'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:23:54] [ForkJoinPool-1-worker-4/WARN]: Mod cobblegen uses the version v2.1b57-BETA which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v2'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:23:54] [ForkJoinPool-1-worker-1/WARN]: Mod flywheel uses the version 0.6.8.a-36 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:23:54] [ForkJoinPool-1-worker-4/WARN]: Mod registrate-fabric uses the version MC1.18.2-1.1.11 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:23:54] [main/WARN]: Mod resolution failed
[18:23:54] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE astralvinery 1.1.1 {depends vinery @ [1.1.4]}, ROOT_FORCELOAD_SINGLE astralvinery 1.1.1]
[18:23:54] [main/INFO]: Reason: [HARD_DEP astralvinery 1.1.1 {depends vinery @ [1.1.4]}]
[18:23:54] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, libipn, fabric-textures-v0, modmenu, continuity, indium, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, numeralping, chat_heads, puzzle, flywheel, fabric-models-v0, fabric-rendering-v0, fallingleaves, fabric-rendering-v1, fabric-key-binding-api-v1, noindium, ctm, disable_custom_worlds_advice]
[18:23:54] [main/INFO]: Fix: add [add:vinery 1.1.4 ([[1.1.4,1.1.4]])], remove [], replace []
[18:23:54] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install vinery, version 1.1.4.
Unmet dependency listing:
	 - Mod 'AstralVinery' (astralvinery) 1.1.1 requires version 1.1.4 of vinery, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.18.2-loader.0.14.22-launcher.0.11.2.jar:0.11.2]
```

Edit:
When having a setup where you don't need to open the zip (e.g. itzg docker) you won't see the notice that you need to add this and another mod.

**Comment by Rivgad** [comment]
Same problem. Found solution: copy mod from client.
But why this even happened?
