### ISSUE TITLE
[Bug]: Server 2.0.5b world not compatible with 2.1

### ISSUE THREAD

**Issue by tomcsojn** [Laskyyy/Create-Astral#378]
### Bug Description

Upgrading server from 2.0.5b breaks the startup process.
Clean setup works well, when setting up the server. when moving the world over it breaks on startup.

### How to Reproduce?

1. Install a clean 2.1 server according to the documentation.
3. copy the world folder into the server folder.  you can download my world from here: https://drive.google.com/file/d/1QOoI9UQYFKx7KoeQWK4saH1HWT0qqgRM/view?usp=sharing
4. start the server.

### Expected Behavior

old worlds could be brought over.
Or have a way of moving it with some changes to the new version.

### Version

2.1

### Logs or additional context

[11:55:22] [main/INFO]: Scripts loaded
[11:55:22] [main/INFO]: Registered custom recipe handler for type kubejs:shaped
[11:55:22] [main/INFO]: Registered custom recipe handler for type kubejs:shapeless
[11:55:22] [main/INFO]: Registered custom recipe handler for type minecraft:crafting_shaped
[11:55:22] [main/INFO]: Registered custom recipe handler for type minecraft:crafting_shapeless
[11:55:22] [main/INFO]: Registered custom recipe handler for type minecraft:stonecutting
[11:55:22] [main/INFO]: Registered custom recipe handler for type minecraft:smelting
[11:55:22] [main/INFO]: Registered custom recipe handler for type minecraft:blasting
[11:55:22] [main/INFO]: Registered custom recipe handler for type minecraft:smoking
[11:55:22] [main/INFO]: Registered custom recipe handler for type minecraft:campfire_cooking
[11:55:22] [main/INFO]: Registered custom recipe handler for type minecraft:smithing
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:alloy_smelter
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:assembling_machine
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:centrifuge
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:chemical_reactor
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:compressor
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:distillation_tower
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:extractor
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:grinder
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:implosion_compressor
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:industrial_electrolyzer
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:recycler
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:scrapbox
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:vacuum_freezer
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:solid_canning_machine
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:wire_mill
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:blast_furnace
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:industrial_grinder
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:industrial_sawmill
[11:55:22] [main/INFO]: Registered custom recipe handler for type techreborn:fluid_replicator
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:sequenced_assembly
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:mechanical_crafting
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:conversion
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:crushing
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:cutting
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:milling
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:basin
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:mixing
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:compacting
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:pressing
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:sandpaper_polishing
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:splashing
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:haunting
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:deploying
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:filling
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:emptying
[11:55:22] [main/INFO]: Registered custom recipe handler for type create:item_application
[11:55:22] [main/INFO]: Registered custom recipe handler for type custommachinery:custom_machine
[11:55:22] [main/INFO]: Registered custom recipe handler for type custommachinery:custom_craft
[11:55:22] [main/INFO]: Scanning recipes...
[11:55:25] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[11:55:25] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/biome]: [nullscape:crystal_peaks, nullscape:shadowlands]
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.1]
Caused by: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/biome]: [nullscape:crystal_peaks, nullscape:shadowlands]
        at net.minecraft.class_2370.method_40276(class_2370.java:325) ~[server-intermediary.jar:?]
        at net.minecraft.class_5455$class_6892.method_40332(class_5455.java:121) ~[server-intermediary.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.minecraft.class_5455$class_6891.<init>(class_5455.java:161) ~[server-intermediary.jar:?]
        at net.minecraft.class_5455.method_40316(class_5455.java:322) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.method_40373(Main.java:167) ~[server-intermediary.jar:?]
        at net.minecraft.class_6904.method_40431(class_6904.java:40) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:155) ~[server-intermediary.jar:?]
        ... 5 more
[11:55:26] [FTB Backups Config Watcher 0/INFO]: Config at D:\astral\config\ftbbackups2.json has changed, reloaded!

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by TwitchTheSniper** [comment]
I also am having this issue as well it has something to do with the biomes changing in the end.  I'm following this [guide](https://www.reddit.com/r/feedthebeast/comments/xu8r12/how_do_i_remove_dimensions_from_my_1182_modpack/)  it tells you to use [NBTexplorer](https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win) to open your world dimension files [like this](![image](https://github.com/user-attachments/assets/9ebdaa09-ff44-4c06-8840-ce60cef19a34)).  I then deleted the entire end [pic](![image](https://github.com/user-attachments/assets/0332ad85-6389-40a9-9e9f-57302b14bf84)). I then saved the edit.
I then made a new world in version 2.1 and opened it in nbtExplorer, the new end has different biomes [pic](![image](https://github.com/user-attachments/assets/7d68a305-b969-4a2d-9a3a-65d00fc77d55)). I then copied the end from the new world, saved it, opened my old world and pasted it in [pic](![image](https://github.com/user-attachments/assets/eb66e3b2-8e80-45fc-a673-c8bb2bb37388)).

this worked for my world.
notes: NBTExplorer copy paste is saved when you open a different world

**Comment by tomcsojn** [comment]
> I also am having this issue as well it has something to do with the biomes changing in the end. I'm following this [guide](https://www.reddit.com/r/feedthebeast/comments/xu8r12/how_do_i_remove_dimensions_from_my_1182_modpack/) it tells you to use [NBTexplorer](https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win) to open your world dimension files [like this](https://github.com/user-attachments/assets/9ebdaa09-ff44-4c06-8840-ce60cef19a34). I then deleted the entire end [pic](https://github.com/user-attachments/assets/0332ad85-6389-40a9-9e9f-57302b14bf84). I then saved the edit. I then made a new world in version 2.1 and opened it in nbtExplorer, the new end has different biomes [pic](https://github.com/user-attachments/assets/7d68a305-b969-4a2d-9a3a-65d00fc77d55). I then copied the end from the new world, saved it, opened my old world and pasted it in [pic](https://github.com/user-attachments/assets/eb66e3b2-8e80-45fc-a673-c8bb2bb37388).
> 
> this worked for my world. notes: MAKE A BACKUP NBTExplorer copy paste is saved when you open a different world


Hey, Thanks a lot for your solution. That actually works well. managed to update everything this way as well.

So it is a suggested workaround :)

**Comment by Erdragh** [comment]
This is caused by us removing the nullscape datapack. When we released 2.1 we did so knowing and intending that worlds aren't compatible, because there's many recipe and progression changes anyway.
