### ISSUE TITLE
[Bug]: Game crash when getting recipe for 'Andesite compound'

### ISSUE THREAD

**Issue by whachoe** [Laskyyy/Create-Astral#482]
### Bug Description

Whenever i press 'r' while highlighting 'Andesite Compound' in REI, the game crashes.

### How to Reproduce?

1. Open up REI
2. Search for andesite compound
3. click the icon of 'andesite compound'
4. Press 'r'

### Version

2.1.2

### Logs or additional context

[17:42:07] [Render thread/ERROR]:Reported exception thrown!net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:886) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
Caused by: java.lang.IllegalArgumentException: fromIndex(216) > toIndex(204)
	at java.util.AbstractList.subListRangeCheck(Unknown Source) ~[?:?]
	at java.util.ArrayList.subList(Unknown Source) ~[?:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.updateEntries(PaginatedEntryListWidget.java:141) ~[RoughlyEnoughItems-8.4.715-fabric.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateEntriesPosition(EntryListWidget.java:266) ~[RoughlyEnoughItems-8.4.715-fabric.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.CollapsingEntryListWidget.updateEntriesPosition(CollapsingEntryListWidget.java:67) ~[RoughlyEnoughItems-8.4.715-fabric.jar:?]
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.updateArea(EntryListWidget.java:251) ~[RoughlyEnoughItems-8.4.715-fabric.jar:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.init(ScreenOverlayImpl.java:177) ~[RoughlyEnoughItems-8.4.715-fabric.jar:?]
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:225) ~[RoughlyEnoughItems-8.4.715-fabric.jar:?]
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:345) ~[RoughlyEnoughItems-8.4.715-fabric.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$method_25394$260(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$dhm000$fancymenu$wrapRenderScreenFancyMenu(class_757.java:5515) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$wrapOperation$dhm000$fancymenu$wrapRenderScreenFancyMenu$261(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$eij001$konkrete$wrapRenderScreenFancyMenu(class_757.java:8535) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:877) ~[client-intermediary.jar:?]

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by whachoe** [comment]
fixed in 2.1.3!
